SELECT * FROM TB_CCTV_INFO;

CREATE TABLE TB_CCTV_CHECK_LOG (
	CCTV_IDX	NUMBER	NOT NULL,
	CHK_DTTM	VARCHAR2(14)	NOT NULL,
	CHK_TP		VARCHAR2(1)	NOT NULL,
	EQUIP_TP	VARCHAR2(1)	NOT NULL,
	DEFECT_YN	VARCHAR2(1)	NOT NULL,
	DEFECT_REASON	VARCHAR2(2000),
	CHK_CMT		VARCHAR2(2000),
	WR_USR_TP	VARCHAR2(1),	
	WR_USR_ID	VARCHAR2(20),	
	WR_DTTM		VARCHAR2(14)
)
TABLESPACE DIGITALCITY;

COMMENT ON COLUMN TB_CCTV_CHECK_LOG.CCTV_IDX IS 'CCTV index';

COMMENT ON COLUMN TB_CCTV_CHECK_LOG. IS '';

COMMENT ON COLUMN TB_CCTV_CHECK_LOG.CHK_DTTM IS '체크일시';
COMMENT ON COLUMN TB_CCTV_CHECK_LOG.CHK_TP IS '체크;
COMMENT ON COLUMN TB_CCTV_CHECK_LOG.EQUIP_TP IS '';
COMMENT ON COLUMN TB_CCTV_CHECK_LOG.DEFECT_YN IS '';
COMMENT ON COLUMN TB_CCTV_CHECK_LOG.DEFECT_REASON IS '';
COMMENT ON COLUMN TB_CCTV_CHECK_LOG.CHK_CMT IS '';
COMMENT ON COLUMN TB_CCTV_CHECK_LOG.WR_USR_TP IS '';
COMMENT ON COLUMN TB_CCTV_CHECK_LOG.WR_USR_ID IS '';
COMMENT ON COLUMN TB_CCTV_CHECK_LOG.WR_DTTM IS '';



		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection “upgrade”;
		proxy_set_header Host $host;